set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(test-project_path "C:/Toolchain/gcc-linaro-7.5.0-2019.12-i686-mingw32_armv8l-linux-gnueabihf")
set(sysroot_target ${test-project_path}/armv8l-linux-gnueabihf/libc)
set(tools ${test-project_path}/bin)
set(CMAKE_C_COMPILER ${tools}/armv8l-linux-gnueabihf-gcc.exe)
set(CMAKE_CXX_COMPILER ${tools}/armv8l-linux-gnueabihf-g++.exe)
set(CMAKE_SYSROOT ${sysroot_target})
SET(CMAKE_CXX_FLAGS " --sysroot=${sysroot_target}")
SET(CMAKE_C_FLAGS ${CMAKE_CXX_FLAGS})
SET(CMAKE_EXE_LINKER_FLAGS "--sysroot=${sysroot_target}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
